import type { Metadata } from "next";
import { Open_Sans, Roboto } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "darhh",
  description: "Generated by create next app",
};

const openSans = Open_Sans({
  subsets: ["latin"], // Specify character subsets
  weight: ["400", "700"], // Specify font weights
  variable: "--font-open-sans", // Specify custom variable name
});

const parkinsans = Roboto({
  subsets: ["latin"], // Specify character subsets
  weight: ["400", "700"], // Specify font weights
  variable: "--font-roboto", // Specify custom variable name
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body
          className={`${openSans.variable} ${parkinsans.variable} overflow-auto overflow-x-hidden bg-gray-50`}
        >
          <div className="flex justify-center">{children}</div>
      </body>
    </html>
  );
}
